import { useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { toast } from 'sonner';
import { Archive, ChevronLeft, ChevronRight, ExternalLink, FileText, GalleryHorizontalEnd, Globe2, RefreshCw, Search } from 'lucide-react';
import { api } from '@/services/api';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Skeleton } from '@/components/ui/skeleton';

type ResourceType='sites'|'galleries'|'invoices';
interface Owner {id:number;name:string;email:string}
interface Site {id:number;user_id:number;site_name:string;slug?:string;is_published:boolean;updated_at:string;user?:Owner}
interface Gallery {id:number;user_id:number;uuid:string;title:string;status:string;photos_count:number;likes_count:number;updated_at:string;user?:Owner}
interface Invoice {id:number;user_id:number;invoice_number:string;client_name:string;client_email:string;status:string;total_amount:number;amount_paid:number;currency:string;issue_date:string;due_date:string;items_count:number;user?:Owner}
interface Meta {current_page:number;last_page:number;total:number;from:number|null;to:number|null}

export default function ResourceControlCenter(){
  const navigate=useNavigate(); const [type,setType]=useState<ResourceType>('sites'); const [items,setItems]=useState<Array<Site|Gallery|Invoice>>([]); const [summary,setSummary]=useState<Record<string,number>>({}); const [statuses,setStatuses]=useState<string[]>([]); const [meta,setMeta]=useState<Meta>({current_page:1,last_page:1,total:0,from:null,to:null}); const [loading,setLoading]=useState(true); const [q,setQ]=useState(''); const [debounced,setDebounced]=useState(''); const [status,setStatus]=useState(''); const [page,setPage]=useState(1); const [reason,setReason]=useState('');
  useEffect(()=>{const timer=window.setTimeout(()=>setDebounced(q.trim()),350);return()=>window.clearTimeout(timer)},[q]);
  useEffect(()=>{setPage(1);setStatus('')},[type]); useEffect(()=>{setPage(1)},[debounced,status]);
  const params=useMemo(()=>({type,q:debounced||undefined,status:status||undefined,page,per_page:30}),[type,debounced,status,page]);
  const load=async()=>{setLoading(true);try{const response=await api.get('/superadmin/resources',{params});setItems(response.data.data??[]);setMeta(response.data.meta);setSummary(response.data.summary??{});setStatuses(response.data.statuses??[])}catch{toast.error('Les ressources ne peuvent pas être chargées.')}finally{setLoading(false)}};
  useEffect(()=>{void load()},[params]);
  const updateSite=async(site:Site)=>{if(reason.trim().length<5)return toast.error('Indiquez le motif de la décision.');try{await api.patch(`/superadmin/resources/sites/${site.id}`,{is_published:!site.is_published,reason});toast.success(site.is_published?'Site dépublié.':'Site publié.');setReason('');await load()}catch(error:any){toast.error(error.response?.data?.message??'Action impossible.')}};
  const updateGallery=async(gallery:Gallery,nextStatus:string)=>{if(reason.trim().length<5)return toast.error('Indiquez le motif de la décision.');try{await api.patch(`/superadmin/resources/galleries/${gallery.id}`,{status:nextStatus,reason});toast.success('État de la galerie mis à jour.');setReason('');await load()}catch(error:any){toast.error(error.response?.data?.message??'Action impossible.')}};
  const tabs=[{key:'sites',label:'Sites',icon:Globe2},{key:'galleries',label:'Galeries',icon:GalleryHorizontalEnd},{key:'invoices',label:'Factures',icon:FileText}] as const;
  const labels:Record<string,string>={total:'Total',published:'Publiés',unpublished:'Non publiés',draft:'Brouillons',archived:'Archivés',billed:'Facturé',paid:'Encaissé',outstanding:'À recevoir'};
  return <main className="mx-auto max-w-[1500px] space-y-6 pb-12"><header className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-emerald-700">Opérations · Inventaire global</p><h1 className="mt-2 text-4xl font-semibold tracking-[-.04em] text-slate-950">Ressources de la plateforme</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Retrouvez les sites, galeries et factures de chaque utilisateur sans changer de contexte.</p></div><Button variant="outline" onClick={()=>void load()}><RefreshCw className="mr-2 h-4 w-4"/>Actualiser</Button></header>
  <nav className="inline-flex rounded-xl bg-slate-950 p-1.5">{tabs.map(({key,label,icon:Icon})=><button key={key} onClick={()=>setType(key)} className={`flex items-center gap-2 rounded-lg px-5 py-2.5 text-sm font-semibold transition ${type===key?'bg-white text-slate-950':'text-slate-400 hover:text-white'}`}><Icon className="h-4 w-4"/>{label}</button>)}</nav>
  <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{Object.entries(summary).slice(0,4).map(([key,value])=><article key={key} className="rounded-2xl bg-white p-5 ring-1 ring-slate-200"><p className="text-xs font-medium text-slate-500">{labels[key]??key}</p><p className="mt-4 text-3xl font-semibold tabular-nums text-slate-950">{['billed','paid','outstanding'].includes(key)?`${Number(value).toLocaleString('fr-FR')} F`:value}</p></article>)}</section>
  <section className="overflow-hidden rounded-2xl bg-white shadow-[0_18px_50px_rgba(15,23,42,.06)] ring-1 ring-slate-200"><div className="border-b border-slate-100 p-5"><div className="grid gap-3 lg:grid-cols-[1fr_220px_1fr]"><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><Input className="pl-9" value={q} onChange={event=>setQ(event.target.value)} placeholder={type==='sites'?'Site, slug, propriétaire…':type==='galleries'?'Galerie, UUID, propriétaire…':'Facture, client, propriétaire…'}/></div><select className="h-10 rounded-md border border-slate-200 px-3 text-sm" value={status} onChange={event=>setStatus(event.target.value)}><option value="">Tous les états</option>{statuses.map(item=><option value={item} key={item}>{item}</option>)}</select>{type!=='invoices'?<Input value={reason} onChange={event=>setReason(event.target.value)} placeholder="Motif avant toute action"/>:<div className="flex items-center rounded-lg bg-amber-50 px-3 text-xs text-amber-800">Les écritures financières sont consultables sans mutation arbitraire.</div>}</div></div>
  <div className="overflow-x-auto">{type==='sites'&&<table className="w-full min-w-[900px] text-sm"><thead className="border-b bg-slate-50/70 text-left text-xs uppercase tracking-wide text-slate-400"><tr><th className="px-5 py-4">Site</th><th>Propriétaire</th><th>URL</th><th>État</th><th>Modification</th><th className="px-5 text-right">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{!loading&&(items as Site[]).map(site=><tr key={site.id} className="hover:bg-slate-50"><td className="px-5 py-4 font-semibold">{site.site_name}</td><td><button className="text-left" onClick={()=>navigate(`/superadmin/users/${site.user_id}`)}><span className="block font-medium">{site.user?.name}</span><span className="text-xs text-slate-400">{site.user?.email}</span></button></td><td className="text-slate-500">/{site.slug}</td><td><span className={`rounded-md px-2 py-1 text-xs font-semibold ${site.is_published?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-600'}`}>{site.is_published?'Publié':'Non publié'}</span></td><td className="text-xs text-slate-500">{new Date(site.updated_at).toLocaleString('fr-FR')}</td><td className="px-5 text-right"><Button size="sm" variant="outline" onClick={()=>void updateSite(site)}>{site.is_published?'Dépublier':'Publier'}</Button>{site.slug&&<a className="ml-2 inline-flex rounded-md border p-2" href={`/${site.slug}`} target="_blank" rel="noreferrer"><ExternalLink className="h-4 w-4"/></a>}</td></tr>)}</tbody></table>}
  {type==='galleries'&&<table className="w-full min-w-[1000px] text-sm"><thead className="border-b bg-slate-50/70 text-left text-xs uppercase tracking-wide text-slate-400"><tr><th className="px-5 py-4">Galerie</th><th>Propriétaire</th><th>Contenu</th><th>État</th><th>Modification</th><th className="px-5 text-right">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{!loading&&(items as Gallery[]).map(gallery=><tr key={gallery.id} className="hover:bg-slate-50"><td className="px-5 py-4"><p className="font-semibold">{gallery.title}</p><p className="font-mono text-xs text-slate-400">{gallery.uuid}</p></td><td><button className="text-left" onClick={()=>navigate(`/superadmin/users/${gallery.user_id}`)}><span className="block font-medium">{gallery.user?.name}</span><span className="text-xs text-slate-400">{gallery.user?.email}</span></button></td><td className="text-slate-500">{gallery.photos_count} photo(s) · {gallery.likes_count} like(s)</td><td><span className="rounded-md bg-slate-100 px-2 py-1 text-xs font-semibold">{gallery.status}</span></td><td className="text-xs text-slate-500">{new Date(gallery.updated_at).toLocaleString('fr-FR')}</td><td className="px-5 text-right"><select value={gallery.status} onChange={event=>void updateGallery(gallery,event.target.value)} className="h-9 rounded-md border border-slate-200 px-2 text-xs"><option value="draft">Brouillon</option><option value="published">Publié</option><option value="archived">Archivé</option></select><a className="ml-2 inline-flex rounded-md border p-2" href={`/g/${gallery.uuid}`} target="_blank" rel="noreferrer"><ExternalLink className="h-4 w-4"/></a></td></tr>)}</tbody></table>}
  {type==='invoices'&&<table className="w-full min-w-[1050px] text-sm"><thead className="border-b bg-slate-50/70 text-left text-xs uppercase tracking-wide text-slate-400"><tr><th className="px-5 py-4">Facture</th><th>Propriétaire</th><th>Client</th><th>Émission</th><th>Total</th><th>Payé</th><th>Solde</th><th>État</th></tr></thead><tbody className="divide-y divide-slate-100">{!loading&&(items as Invoice[]).map(invoice=><tr key={invoice.id} className="cursor-pointer hover:bg-slate-50" onClick={()=>navigate(`/superadmin/users/${invoice.user_id}`)}><td className="px-5 py-4"><p className="font-semibold">{invoice.invoice_number}</p><p className="text-xs text-slate-400">{invoice.items_count} ligne(s)</p></td><td><p className="font-medium">{invoice.user?.name}</p><p className="text-xs text-slate-400">{invoice.user?.email}</p></td><td><p>{invoice.client_name}</p><p className="text-xs text-slate-400">{invoice.client_email}</p></td><td className="text-slate-500">{new Date(invoice.issue_date).toLocaleDateString('fr-FR')}</td><td className="font-semibold tabular-nums">{Number(invoice.total_amount).toLocaleString('fr-FR')} {invoice.currency}</td><td className="tabular-nums text-emerald-700">{Number(invoice.amount_paid??0).toLocaleString('fr-FR')}</td><td className="tabular-nums text-amber-700">{Math.max(0,Number(invoice.total_amount)-Number(invoice.amount_paid??0)).toLocaleString('fr-FR')}</td><td>{invoice.status}</td></tr>)}</tbody></table>}
  {loading&&<div className="space-y-2 p-5">{Array.from({length:7}).map((_,index)=><Skeleton key={index} className="h-14 w-full"/>)}</div>}{!loading&&items.length===0&&<div className="py-20 text-center"><Archive className="mx-auto h-10 w-10 text-slate-300"/><p className="mt-4 font-semibold">Aucune ressource trouvée</p><p className="text-sm text-slate-500">Modifiez la recherche ou les filtres.</p></div>}</div>
  <footer className="flex items-center justify-between border-t border-slate-100 px-5 py-4"><p className="text-sm text-slate-500">{meta.from??0}–{meta.to??0} sur {meta.total}</p><div className="flex items-center gap-2"><Button size="sm" variant="outline" disabled={page<=1} onClick={()=>setPage(value=>value-1)}><ChevronLeft className="h-4 w-4"/></Button><span className="text-sm tabular-nums">{meta.current_page}/{meta.last_page}</span><Button size="sm" variant="outline" disabled={page>=meta.last_page} onClick={()=>setPage(value=>value+1)}><ChevronRight className="h-4 w-4"/></Button></div></footer></section></main>
}
