import { useEffect, useMemo, useState } from 'react';
import { Activity, ChevronLeft, ChevronRight, Clock3, Filter, History, Search, ShieldAlert, UserRound } from 'lucide-react';
import { toast } from 'sonner';
import { api } from '@/services/api';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { Skeleton } from '@/components/ui/skeleton';

interface AuditLog { id:number; action:string; target_type?:string; target_id?:number; reason?:string; ip_address?:string; created_at:string; actor?:{name:string;email:string} }
interface Meta { current_page:number; last_page:number; total:number; from:number|null; to:number|null }
const labels:Record<string,string>={'user.created':'Compte créé','user.updated':'Compte modifié','user.deleted':'Compte supprimé','user.activated':'Compte réactivé','user.deactivated':'Compte suspendu','user.sessions_revoked':'Sessions révoquées','user.email_verified':'Email vérifié','user.email_unverified':'Vérification retirée','subscription.assigned':'Abonnement attribué','subscription.updated':'Abonnement modifié','site.published':'Site publié','site.unpublished':'Site dépublié'};

export default function SuperAdminAuditLog(){
  const [logs,setLogs]=useState<AuditLog[]>([]); const [actions,setActions]=useState<string[]>([]); const [summary,setSummary]=useState({today:0,last_7_days:0,sensitive:0}); const [meta,setMeta]=useState<Meta>({current_page:1,last_page:1,total:0,from:null,to:null});
  const [query,setQuery]=useState(''); const [debounced,setDebounced]=useState(''); const [action,setAction]=useState(''); const [from,setFrom]=useState(''); const [to,setTo]=useState(''); const [page,setPage]=useState(1); const [loading,setLoading]=useState(true);
  useEffect(()=>{const timer=window.setTimeout(()=>setDebounced(query.trim()),350);return()=>window.clearTimeout(timer)},[query]);
  const params=useMemo(()=>({q:debounced||undefined,action:action||undefined,from:from||undefined,to:to||undefined,page,per_page:30}),[debounced,action,from,to,page]);
  useEffect(()=>{setPage(1)},[debounced,action,from,to]);
  useEffect(()=>{setLoading(true);api.get('/superadmin/audit-logs',{params}).then(response=>{setLogs(response.data.data??[]);setMeta(response.data.meta);setActions(response.data.actions??[]);setSummary(response.data.summary??summary)}).catch(()=>toast.error('Le journal d’audit ne peut pas être chargé.')).finally(()=>setLoading(false))},[params]);
  return <main className="mx-auto max-w-[1500px] space-y-6 pb-12"><header><p className="text-xs font-semibold uppercase tracking-[.18em] text-emerald-700">Gouvernance · Traçabilité</p><h1 className="mt-2 text-4xl font-semibold tracking-[-.04em] text-slate-950">Journal des décisions</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Chaque action sensible du centre de contrôle est enregistrée avec son acteur, sa cible, son motif et son origine.</p></header>
  <section className="grid gap-3 md:grid-cols-3">{[["Aujourd’hui",summary.today,Clock3],["7 derniers jours",summary.last_7_days,Activity],["Actions sensibles · 30 j",summary.sensitive,ShieldAlert]].map(([label,value,Icon]:any)=><article key={label} className="rounded-2xl bg-white p-5 ring-1 ring-slate-200"><Icon className="h-5 w-5 text-emerald-700"/><p className="mt-5 text-3xl font-semibold tabular-nums">{value}</p><p className="text-sm text-slate-500">{label}</p></article>)}</section>
  <section className="overflow-hidden rounded-2xl bg-white shadow-[0_18px_50px_rgba(15,23,42,.06)] ring-1 ring-slate-200"><div className="border-b border-slate-100 p-5"><div className="grid gap-3 lg:grid-cols-[1fr_240px_180px_180px]"><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><Input className="pl-9" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Action, motif ou opérateur…"/></div><select value={action} onChange={event=>setAction(event.target.value)} className="h-10 rounded-md border border-slate-200 px-3 text-sm"><option value="">Toutes les actions</option>{actions.map(item=><option key={item} value={item}>{labels[item]??item}</option>)}</select><Input type="date" value={from} onChange={event=>setFrom(event.target.value)} aria-label="Date de début"/><Input type="date" value={to} onChange={event=>setTo(event.target.value)} aria-label="Date de fin"/></div><div className="mt-3 flex items-center gap-2 text-xs text-slate-400"><Filter className="h-3.5 w-3.5"/>Les filtres se combinent et restent appliqués pendant la pagination.</div></div>
  <div className="overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead className="border-b bg-slate-50/70 text-left text-xs uppercase tracking-wide text-slate-400"><tr><th className="px-5 py-4">Date</th><th className="px-5 py-4">Décision</th><th className="px-5 py-4">Opérateur</th><th className="px-5 py-4">Cible</th><th className="px-5 py-4">Motif</th><th className="px-5 py-4">IP</th></tr></thead><tbody className="divide-y divide-slate-100">{loading&&Array.from({length:7}).map((_,i)=><tr key={i}>{Array.from({length:6}).map((__,j)=><td className="px-5 py-4" key={j}><Skeleton className="h-7 w-full"/></td>)}</tr>)}{!loading&&logs.map(log=><tr key={log.id} className="hover:bg-slate-50"><td className="px-5 py-4 text-xs tabular-nums text-slate-500">{new Date(log.created_at).toLocaleString('fr-FR')}</td><td className="px-5 py-4 font-semibold text-slate-900">{labels[log.action]??log.action}</td><td className="px-5 py-4"><span className="flex items-center gap-2"><UserRound className="h-4 w-4 text-slate-400"/>{log.actor?.name??'Système'}</span><span className="ml-6 block text-xs text-slate-400">{log.actor?.email}</span></td><td className="px-5 py-4 text-slate-600">{log.target_type&&log.target_id?`${log.target_type} #${log.target_id}`:'—'}</td><td className="max-w-sm px-5 py-4 text-slate-600">{log.reason??'Non renseigné'}</td><td className="px-5 py-4 font-mono text-xs text-slate-400">{log.ip_address??'—'}</td></tr>)}</tbody></table>{!loading&&logs.length===0&&<div className="py-20 text-center"><History className="mx-auto h-10 w-10 text-slate-300"/><p className="mt-4 font-semibold">Aucune décision trouvée</p><p className="text-sm text-slate-500">Modifiez les filtres pour élargir la recherche.</p></div>}</div>
  <footer className="flex items-center justify-between border-t border-slate-100 px-5 py-4"><p className="text-sm text-slate-500">{meta.from??0}–{meta.to??0} sur {meta.total}</p><div className="flex items-center gap-2"><Button size="sm" variant="outline" disabled={page<=1} onClick={()=>setPage(value=>value-1)}><ChevronLeft className="h-4 w-4"/></Button><span className="text-sm tabular-nums">{meta.current_page}/{meta.last_page}</span><Button size="sm" variant="outline" disabled={page>=meta.last_page} onClick={()=>setPage(value=>value+1)}><ChevronRight className="h-4 w-4"/></Button></div></footer></section></main>
}
